version: "3.7"
services:

  client-envoy:
    build:
      context: .
      dockerfile: Dockerfile-client
    volumes:
      - ./client-envoy.yaml:/etc/client-envoy.yaml
      - ./envoy-static:/usr/local/bin/envoy
    networks:
      - envoymesh
    expose:
      - "6666"
    ports:
      - "6666:6666"
      - "8001:8001"

networks:
  envoymesh: {}
